/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SmartHeadingPastePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  avoidH1WhenNoContext: true,
  showNotification: true,
  maxHeadingLevel: 6,
  skipCodeBlocks: true
};
var LEADING_NOISE_RE = /^[\s\p{Cf}\p{Zs}]*/u;
var HEADING_LEVEL_FROM_START_RE = /^(#{1,6}|＃{1,6})(?:[\s\p{Cf}\p{Zs}]|$)/u;
var HEADING_PARSE_RE = /^([\s\p{Cf}\p{Zs}]*)((?:#{1,6}|＃{1,6}))(.*)$/u;
var SmartHeadingPastePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.lastPastedText = "";
    this.lastPasteTime = 0;
    // ==================== 核心粘贴处理器 ====================
    this.handlePaste = (event, editor, view) => {
      this.processPasteEvent(event, editor, "editor-paste");
    };
    this.handleDomPaste = (event) => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (!activeView)
        return;
      const activeElement = document.activeElement;
      if (!(activeElement instanceof HTMLElement))
        return;
      if (!activeElement.closest(".markdown-source-view, .cm-editor, .cm-content"))
        return;
      this.processPasteEvent(event, activeView.editor, "dom-paste");
    };
  }
  async onload() {
    await this.loadSettings();
    console.log("Smart Heading Paste \u63D2\u4EF6\u5DF2\u52A0\u8F7D");
    this.registerEvent(
      this.app.workspace.on("editor-paste", this.handlePaste)
    );
    this.registerDomEvent(document, "paste", this.handleDomPaste);
    this.addSettingTab(new SmartPasteSettingTab(this.app, this));
    this.addCommand({
      id: "smart-paste-command",
      name: "\u667A\u80FD\u7C98\u8D34\uFF08\u8C03\u6574\u6807\u9898\u5C42\u7EA7\uFF09",
      hotkeys: [{ modifiers: ["Mod", "Shift"], key: "v" }],
      editorCallback: (editor) => {
        this.manualSmartPaste(editor);
      }
    });
  }
  onunload() {
    console.log("Smart Heading Paste \u63D2\u4EF6\u5DF2\u5378\u8F7D");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  processPasteEvent(event, editor, source) {
    if (event.defaultPrevented) {
      console.log(`Smart Heading Paste (${source}): paste marked handled, still checking`);
    }
    const clipboardData = event.clipboardData;
    if (!clipboardData)
      return;
    const pastedText = clipboardData.getData("text/plain");
    if (!pastedText)
      return;
    const now = Date.now();
    if (pastedText === this.lastPastedText && now - this.lastPasteTime < 250) {
      event.preventDefault();
      event.stopPropagation();
      console.log(`Smart Heading Paste (${source}): deduping duplicate paste event`);
      return;
    }
    if (!this.containsMarkdownHeadings(pastedText)) {
      return;
    }
    event.preventDefault();
    event.stopPropagation();
    this.lastPastedText = pastedText;
    this.lastPasteTime = now;
    console.log(`Smart Heading Paste (${source}): intercepting paste`);
    const cursor = editor.getCursor();
    this.performSmartPaste(editor, pastedText, cursor.line);
  }
  // ==================== 手动智能粘贴 ====================
  async manualSmartPaste(editor) {
    try {
      const text = await navigator.clipboard.readText();
      console.log("[Smart Heading Paste] \u624B\u52A8\u7C98\u8D34\u89E6\u53D1");
      if (!this.containsMarkdownHeadings(text)) {
        console.log("[Smart Heading Paste] \u624B\u52A8\u7C98\u8D34\u5185\u5BB9\u65E0\u6807\u9898\uFF0C\u76F4\u63A5\u63D2\u5165");
        editor.replaceSelection(text);
        return;
      }
      const cursor = editor.getCursor();
      this.performSmartPaste(editor, text, cursor.line);
    } catch (err) {
      new import_obsidian.Notice("\u65E0\u6CD5\u8BFB\u53D6\u526A\u8D34\u677F\u5185\u5BB9");
    }
  }
  // ==================== 核心逻辑 ====================
  performSmartPaste(editor, content, currentLine) {
    const contextLevel = this.getContextHeadingLevel(editor, currentLine);
    console.log(`[Smart Heading Paste] \u4E0A\u6587\u6807\u9898\u5C42\u7EA7: ${contextLevel === 0 ? "\u65E0 (\u6587\u6863\u6839)" : "H" + contextLevel}`);
    const parsed = this.parseHeadings(content);
    if (!parsed.hasHeading) {
      console.log("[Smart Heading Paste] \u7C98\u8D34\u5185\u5BB9\u65E0\u6807\u9898\uFF0C\u76F4\u63A5\u63D2\u5165");
      editor.replaceSelection(content);
      return;
    }
    console.log(`[Smart Heading Paste] \u7C98\u8D34\u5185\u5BB9\u6807\u9898\u7EDF\u8BA1: \u6700\u5C0FH${parsed.minLevel}, \u6700\u5927H${parsed.maxLevel}, \u5171${parsed.headings.length}\u4E2A\u6807\u9898`);
    let targetBaseLevel;
    if (contextLevel === 0) {
      targetBaseLevel = this.settings.avoidH1WhenNoContext ? 2 : 1;
    } else {
      targetBaseLevel = contextLevel + 1;
    }
    targetBaseLevel = Math.max(1, Math.min(this.settings.maxHeadingLevel, targetBaseLevel));
    const offset = targetBaseLevel - parsed.minLevel;
    console.log(`[Smart Heading Paste] \u76EE\u6807\u5C42\u7EA7: H${targetBaseLevel}, \u539F\u59CB\u6700\u5C0F\u5C42\u7EA7: H${parsed.minLevel}, \u504F\u79FB\u91CF: ${offset > 0 ? "+" : ""}${offset}`);
    const adjustedContent = this.applyHeadingOffset(
      content,
      offset,
      this.settings.skipCodeBlocks
    );
    const hasModified = adjustedContent !== content;
    console.log(`[Smart Heading Paste] \u662F\u5426\u505A\u4E86\u4FEE\u6539: ${hasModified ? "\u662F" : "\u5426"}`);
    editor.replaceSelection(adjustedContent);
    if (this.settings.showNotification) {
      const contextStr = contextLevel === 0 ? "\u6587\u6863\u6839" : `H${contextLevel}`;
      const details = offset === 0 ? "\u65E0\u9700\u8C03\u6574" : `\u504F\u79FB ${offset > 0 ? "+" : ""}${offset} \u7EA7`;
      new import_obsidian.Notice(`\u7C98\u8D34\u8C03\u6574: ${contextStr} \u2192 H${targetBaseLevel} (${details})`, 3e3);
    }
  }
  // ==================== 工具方法 ====================
  /**
   * 检查文本是否包含 Markdown 标题（排除代码块）
   */
  containsMarkdownHeadings(text) {
    const lines = text.split(/\r\n|\r|\n/);
    let inCodeBlock = false;
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.startsWith("```")) {
        inCodeBlock = !inCodeBlock;
        continue;
      }
      if (!inCodeBlock && this.extractHeadingLevel(line) > 0) {
        return true;
      }
    }
    return false;
  }
  /**
   * 获取当前光标所在位置的上下文标题级别
   * 向上查找最近的标题（1-6），没找到返回 0
   */
  getContextHeadingLevel(editor, currentLine) {
    let fenceCount = 0;
    for (let i = 0; i <= currentLine; i++) {
      const trimmed = editor.getLine(i).trim();
      if (trimmed.startsWith("```")) {
        fenceCount++;
      }
    }
    let inCodeBlock = fenceCount % 2 === 1;
    for (let i = currentLine; i >= 0; i--) {
      const line = editor.getLine(i);
      const trimmed = line.trim();
      if (trimmed.startsWith("```")) {
        inCodeBlock = !inCodeBlock;
        continue;
      }
      if (inCodeBlock)
        continue;
      const level = this.extractHeadingLevel(line);
      if (level > 0) {
        console.log(`[Smart Heading Paste] \u627E\u5230\u4E0A\u6587\u6807\u9898: H${level} at line ${i + 1}: ${line.trim()}`);
        return level;
      }
    }
    console.log("[Smart Heading Paste] \u672A\u627E\u5230\u4E0A\u6587\u6807\u9898\uFF0C\u8FD4\u56DE\u6587\u6863\u6839");
    return 0;
  }
  /**
   * 解析粘贴内容中的标题信息
   */
  parseHeadings(content) {
    const lines = content.split(/\r\n|\r|\n/);
    let inCodeBlock = false;
    let minLevel = 6;
    let maxLevel = 1;
    let hasHeading = false;
    const headings = [];
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmed = line.trim();
      if (trimmed.startsWith("```")) {
        inCodeBlock = !inCodeBlock;
        continue;
      }
      if (!inCodeBlock || !this.settings.skipCodeBlocks) {
        const parsedLine = this.parseHeadingLine(line);
        if (parsedLine) {
          const level = parsedLine.level;
          hasHeading = true;
          minLevel = Math.min(minLevel, level);
          maxLevel = Math.max(maxLevel, level);
          headings.push({ line: i, level, text: parsedLine.content.trim() });
        }
      }
    }
    return { hasHeading, minLevel, maxLevel, headings };
  }
  /**
   * 应用标题偏移量
   * @param offset 正数增加 #，负数减少 #
   * @param skipCodeBlocks 是否跳过代码块内的标题
   */
  applyHeadingOffset(content, offset, skipCodeBlocks) {
    if (offset === 0) {
      console.log("[Smart Heading Paste] applyHeadingOffset: \u504F\u79FB\u91CF\u4E3A0\uFF0C\u65E0\u9700\u8C03\u6574");
      return content;
    }
    const lines = content.split(/\r\n|\r|\n/);
    let inCodeBlock = false;
    return lines.map((line, index) => {
      const trimmed = line.trim();
      if (trimmed.startsWith("```")) {
        inCodeBlock = !inCodeBlock;
        return line;
      }
      if (inCodeBlock && skipCodeBlocks)
        return line;
      const parsedLine = this.parseHeadingLine(line);
      if (parsedLine) {
        const indent = parsedLine.prefix;
        const currentLevel = parsedLine.level;
        const content2 = parsedLine.content;
        let newLevel = currentLevel + offset;
        newLevel = Math.max(1, Math.min(this.settings.maxHeadingLevel, newLevel));
        const result = indent + "#".repeat(newLevel) + content2;
        console.log(`[Smart Heading Paste] \u8C03\u6574\u7B2C${index + 1}\u884C: H${currentLevel} -> H${newLevel} | ${result.trim()}`);
        return result;
      }
      return line;
    }).join("\n");
  }
  /**
   * 从行首提取 ATX 标题级别（1-6），无法识别返回 0
   */
  extractHeadingLevel(line) {
    const normalized = line.replace(LEADING_NOISE_RE, "");
    const match = normalized.match(HEADING_LEVEL_FROM_START_RE);
    return match ? match[1].replace(/＃/g, "#").length : 0;
  }
  /**
   * 解析一行标题，返回前缀、级别和标题正文
   */
  parseHeadingLine(line) {
    var _a;
    const match = line.match(HEADING_PARSE_RE);
    if (!match)
      return null;
    const rest = (_a = match[3]) != null ? _a : "";
    if (rest.length > 0 && !/^[\s\p{Cf}\p{Zs}]/u.test(rest)) {
      return null;
    }
    return {
      prefix: match[1],
      level: match[2].replace(/＃/g, "#").length,
      content: rest
    };
  }
};
var SmartPasteSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u667A\u80FD\u7C98\u8D34\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u907F\u514D\u6587\u6863\u6839\u7EA7\u522B H1").setDesc("\u5F53\u7C98\u8D34\u4F4D\u7F6E\u6CA1\u6709\u4E0A\u7EA7\u6807\u9898\u65F6\uFF0C\u81EA\u52A8\u5C06 H1 \u8F6C\u4E3A H2\uFF08\u907F\u514D\u4E0E\u6587\u6863\u6807\u9898\u51B2\u7A81\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.avoidH1WhenNoContext).onChange(async (value) => {
      this.plugin.settings.avoidH1WhenNoContext = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u663E\u793A\u8C03\u6574\u63D0\u793A").setDesc("\u7C98\u8D34\u540E\u663E\u793A\u6807\u9898\u5C42\u7EA7\u8C03\u6574\u8BE6\u60C5").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotification).onChange(async (value) => {
      this.plugin.settings.showNotification = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u8DF3\u8FC7\u4EE3\u7801\u5757").setDesc("\u4E0D\u8C03\u6574\u4EE3\u7801\u5757\u5185\u7684 # \u5B57\u7B26\uFF08\u5982 Python \u6CE8\u91CA\u3001Shell \u914D\u7F6E\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.skipCodeBlocks).onChange(async (value) => {
      this.plugin.settings.skipCodeBlocks = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6700\u5927\u6807\u9898\u7EA7\u522B").setDesc("\u9650\u5236\u6807\u9898\u6700\u9AD8\u7EA7\u522B\uFF08\u901A\u5E38\u4FDD\u6301 6\uFF09").addSlider((slider) => slider.setLimits(1, 6, 1).setValue(this.plugin.settings.maxHeadingLevel).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxHeadingLevel = value;
      await this.plugin.saveSettings();
    }));
  }
};
